dist:     trusty
sudo:     required

language: c 


os:
  - linux

compiler:
  # ... и с помощью GCC, и Clang
  - gcc

addons:
  apt:
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - python2.7
      - libgtest-dev
      - lcov

script:
  # скрипт сборки и тестирования проекта:
  - pip install --user cpp-coveralls
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ctest
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --tool=memcheck --leak-check=yes ctest ; fi
  - cd ..
  - rm -rf build
  - mkdir build
  - cd build
  - cmake -DENABLE_PARALLEL=ON -DENABLE_COVERAGE=ON ..
  - cmake --build .
  - ctest
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --tool=memcheck --leak-check=yes ctest ; fi
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --enable=all --error-exitcode=1 -I include --suppress=missingIncludeSystem ./parallel_lib ./consistent_lib/include/*.h --check-config ; fi