dist:     trusty    
sudo:     required  
language: c      

os:
  - linux


compiler:
  
  - gcc


addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - valgrind
      - cppcheck
      - make
      - cmake
      - lcov
      - gcc-7
      - g++-7
      - libgtest-dev



script:
  # скрипт сборки и тестирования проекта:
  - pip install --user cpp-coveralls
  - sudo ln -s /usr/bin/gcc-7 /usr/local/bin/gcc
  - sudo ln -s /usr/bin/g++-7 /usr/local/bin/g++
  - export CC=/usr/bin/gcc-7
  - export CXX=/usr/bin/g++-7
  - mkdir - p build
  - cd build
  - cmake -DENABLE_PARALLEL=ON -DENABLE_COVERAGE=ON ..
  - cmake --build .
  - ctest --output-on-failure
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --tool=memcheck --leak-check=yes ./test/project_test ; fi
  - cd ..
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then cppcheck --enable=all --error-exitcode=1 -I include --suppress=missingIncludeSystem ../src ../include/*.h --check-config ; fi
 after_success:
  - coveralls --root .. --build-root . -E ".*CMakeFiles.*" -E ".*googletest*" --gcov /usr/bin/gcov --gcov-options '\-lp